version: '3'
services:

  cineclubadministration-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cineclubadministration
    ports:
      - 33061:3306

  accountmanagement-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cineclubaccountmanagment
    ports:
      - 33062:3306

  showtimecontext-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: showtimecontext
    ports:
      - 33063:3306


  reservationpurchase-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: reservationpurchase
    ports:
      - 33064:3306

  comments-db:
    image: mongo:latest
    environment:
        MONGO_INITDB_DATABASE: comments
    ports:
      - 27018:27017

  discovery:
    image: discovery-service:latest
    ports:
      - 8761:8761

  config:
    image: config-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    ports:
      - 8888:8888

  api-gateway:
    image: api-gateway-service:latest
    restart: on-failure
    environment:

      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8080:8080

  account-management-service:
    restart: on-failure
    image: account-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8082:8082
  cineclub-administration-service:
    restart: on-failure
    image: cineclub-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8081:8081

  reservation-service:
    restart: on-failure
    image: reservation-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config

  showtime-service:
    restart: on-failure
    image: showtime-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8084:8084

  comments-service:
    restart: on-failure
    image: comments-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8085:8085