version: '3'
services:

  cineclubadministration-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cineclubadministration
    ports:
        - 3306:3306

  accountmanagement-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: cineclubaccountmanagment
    ports:
        - 3307:3306

  discovery:
    image: discovery-service:latest
    ports:
      - 8761:8761
    #networks:
    #  - tucineproject_default

  config:
    image: config-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
    ports:
      - 8888:8888

  api-gateway:
    image: api-gateway-service:latest
    restart: always
    environment:
      # Agrega la siguiente línea para que el servicio api-gateway pueda reconocer el servidor Eureka
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8080:8080

  account-management-service:
    restart: always
    image: account-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config

  cineclub-administration-service:
    image: cineclub-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8081:8081

  reservation-service:
    image: reservation-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config

  showtime-service:
    image: showtime-service:latest
    environment:
      - EUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
